WIP on upgrade to expo sdk 50
Error: Call to function 'ExpoMds.subscribe' has been rejected.
→ Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void com.movesense.mds.SDSInternalWrapper.sdsSetDelegate(java.lang.Object) (tried Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate and Java_com_movesense_mds_SDSInternalWrapper_sdsSetDelegate__Ljava_lang_Object_2)